### ISSUE TITLE
Add different time zone warning

### ISSUE THREAD

**Issue by cbrxyz** [jm6087/wme-closure-helper#29]
Add a warning if the user is in a different time zone for the closure they are applying

**Comment by jm6087** [comment]
Not sure if possible but my thought on this would be:

If your script is not changing the start date/time because of preset option then compare editor time zone to the closure location time zone and automatically adjust the that start date/time to the closure time zone.  Maybe add an option if the editor does not want to do this (but IMO, that make no sense since it could cause issues)

**Comment by jm6087** [comment]
If time zone is ahead of me, not sure if any adjustments need to be made.

If I have a Crash Preset for 90m and I press the Crash button on a closure in a time zone 2 hours behind me, the start date/time needs to be adjusted 2 hours backward but the 90 minutes closure needs to start now.

i.e.  Closure added at 10am central for CA.  Start time needs to adjust to 8am to make it live, 90m needs to start at 10am Central.

Hope that is clear as mud

**Comment by cbrxyz** [comment]
Requested to be optional setting
